// Code generated by MockGen. DO NOT EDIT.
// Source: order.go

// Package imdb is a generated GoMock package.
package imdb

import (
	context "context"
	reflect "reflect"

	"github.com/bagardavidyanisntreal/go-lessons/goappdesignintro/example/model/order"
	gomock "github.com/golang/mock/gomock"
)

// Mocknext is a mock of next interface.
type Mocknext struct {
	ctrl     *gomock.Controller
	recorder *MocknextMockRecorder
}

// MocknextMockRecorder is the mock recorder for Mocknext.
type MocknextMockRecorder struct {
	mock *Mocknext
}

// NewMocknext creates a new mock instance.
func NewMocknext(ctrl *gomock.Controller) *Mocknext {
	mock := &Mocknext{ctrl: ctrl}
	mock.recorder = &MocknextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocknext) EXPECT() *MocknextMockRecorder {
	return m.recorder
}

// OrderByID mocks base method.
func (m *Mocknext) OrderByID(ctx context.Context, id int64) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderByID", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderByID indicates an expected call of OrderByID.
func (mr *MocknextMockRecorder) OrderByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderByID", reflect.TypeOf((*Mocknext)(nil).OrderByID), ctx, id)
}

// UpdateOrder mocks base method.
func (m *Mocknext) UpdateOrder(ctx context.Context, order *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MocknextMockRecorder) UpdateOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*Mocknext)(nil).UpdateOrder), ctx, order)
}
